name: Node

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: cache deps and built sources
        uses: actions/cache@main
        with:
          path: |
            node_modules
            build
            types
          key: ${{ runner.os }}-${{ github.sha }}

      - name: install deps
        run: yarn

      - name: build
        run: yarn build

      - name: lint
        run: yarn lint

  test-common:
    needs: build

    env:
      DIR: common/**

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: restore cache
        uses: actions/cache@main
        with:
          path: |
            node_modules
            build
            types
          key: ${{ runner.os }}-${{ github.sha }}

      - name: test
        run: yarn test test/$DIR/*.ts

  test-dev:
    needs: build

    env:
      DIR: dev

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: restore cache
        uses: actions/cache@main
        with:
          path: |
            node_modules
            build
            types
          key: ${{ runner.os }}-${{ github.sha }}

      - name: test
        run: yarn test test/$DIR/*.ts

  test-lockup:
    needs: build

    env:
      DIR: lockup

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: restore cache
        uses: actions/cache@main
        with:
          path: |
            node_modules
            build
            types
          key: ${{ runner.os }}-${{ github.sha }}

      - name: test
        run: yarn test test/$DIR/*.ts

  test-market:
    needs: build

    env:
      DIR: market

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: restore cache
        uses: actions/cache@main
        with:
          path: |
            node_modules
            build
            types
          key: ${{ runner.os }}-${{ github.sha }}

      - name: test
        run: yarn test test/$DIR/*.ts

  test-metrics:
    needs: build

    env:
      DIR: metrics

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: restore cache
        uses: actions/cache@main
        with:
          path: |
            node_modules
            build
            types
          key: ${{ runner.os }}-${{ github.sha }}

      - name: test
        run: yarn test test/$DIR/*.ts

  test-policy:
    needs: build

    env:
      DIR: policy

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: restore cache
        uses: actions/cache@main
        with:
          path: |
            node_modules
            build
            types
          key: ${{ runner.os }}-${{ github.sha }}

      - name: test
        run: yarn test test/$DIR/*.ts

  test-property:
    needs: build

    env:
      DIR: property

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: restore cache
        uses: actions/cache@main
        with:
          path: |
            node_modules
            build
            types
          key: ${{ runner.os }}-${{ github.sha }}

      - name: test
        run: yarn test test/$DIR/*.ts

  test-sToken:
    needs: build

    env:
      DIR: s-token

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: restore cache
        uses: actions/cache@main
        with:
          path: |
            node_modules
            build
            types
          key: ${{ runner.os }}-${{ github.sha }}

      - name: test
        run: yarn test test/$DIR/*.ts

  test-withdraw:
    needs: build

    env:
      DIR: withdraw

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: restore cache
        uses: actions/cache@main
        with:
          path: |
            node_modules
            build
            types
          key: ${{ runner.os }}-${{ github.sha }}

      - name: test
        run: yarn test test/$DIR/*.ts
